### ISSUE TITLE
Output function - Add support for parent child relations

### ISSUE THREAD

**Issue by silvandiepen** [MatiseAms/henris#19]
for instance when using this:
```scss
@if output('button-regular'){
	.button--regular{
		font-size: 1rem; 
	}
}
```
with settings:
```json
{
	"output": [
		{
			"button": false,
			"button-regular": true
		}
	]
}
```
Will not be outputed. Because the "parent": button is set to false. Parents are defined by the key before the first dash (-).  In this way its easier to enable a whole set of "children" in once or exclude. 

```json
{
	"output": [
		{
			"button": true,
			"button-regular": false
		}
	]
}
```
will also NOT output the button. Only when both are `true` the child will be outputed.
