### ISSUE TITLE
Feature request: color classes

### ISSUE THREAD

**Issue by Sidstumple** [MatiseAms/henris#3]
## Issue
I miss this function

## Proposal
```scss
// Create Background Classes
@if variable-exists("custom-colors") {
	$colors: map-merge($colors, $custom-colors);
}

@debug($colors);

@each $name, $value in $colors {
	$name-lowercase: to-lower-case($name);
	.bg-#{$name},
	.bg-#{$name-lowercase} {
		background-color: $value;
		color: contra($value);
		.copy-button svg path {
			fill: contra($value);
		}
		hr {
			background-color: currentColor;
			color: currentColor;
		}
	}
	.text-#{$name},
	.text-#{$name-lowercase},
	.content .text-#{$name-lowercase} {
		color: $value !important;
	}
	$opacity: (0.9, 0.8, 0.75, 0.7, 0.6, 0.5, 0.4, 0.3, 0.25, 0.2, 0.1);
	@each $opacity-value in $opacity {
		$opacity-name: "0#{$opacity-value * 100}";
		.bg-#{$name}-#{$opacity-name},
		.bg-#{$name-lowercase}-#{$opacity-name} {
			background-color: color($name, $opacity-value);
			color: $value;
		}
	}
}
```
